name: workflow_overview

on:
 workflow_dispatch:
 push:
  branches:
   -main


jobs:
  my_self_hosted_job:
   name: my self job hosted
   runs-on: self-hosted
   steps:
      - name: name of my step
        id: stepId
        shell: cmd
        run: |
         echo this is a multiline command
         echo here we go again
         echo heyooo
   
  a_simple_job:
    name: my simple job
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "Hello world"
      - name: name of my second step
        id: ShellId
        shell: python
        run: print("This is my second step ")
  
