# name of the workflow
name: workflow_overview

# Triggers
on:
 # It triggers when the i manually run the workflow
 workflow_dispatch:
 # It triggers once the file is commited
 push:
 # Concerned branches
  branches:
   -main

# Tasks we gonna automate
jobs:
# Name of the task 1
  my_self_hosted_job:
   name: my self job hosted
   # This task is going to run on a self hosted image (self hosted runner)
   runs-on: self-hosted
   # Steps of the job
   steps:
      - name: name of my step
        id: stepId
        shell: cmd
        run: |
         echo this is a multiline command
         echo here we go again
         echo heyooo
  # Name of the task 2
  a_simple_job:
    name: my simple job
    # This task is going to run on ubuntu on github
    runs-on: ubuntu-latest
    steps:
      # first step
      - name: name of my step
        id: stepId
        run: echo "Hello world"
       # second step
      - name: name of my second step
        id: ShellId
        shell: python
        run: print("This is my second step ")
  
